from __future__ import annotations
from datetime import datetime
from pathlib import Path
from typing import Dict, Any
from .base_agent import BaseAgent

REPORT_SYSTEM = """You are the Content Agent. Write polished professional business reports.

Structure:
# [Report Title]
**Prepared by:** AI Business Operator | **Date:** {date}

---
## Executive Summary
## Market Overview
## Competitive Analysis
## Key Trends & Insights
## SWOT Analysis
## Strategic Recommendations
## Conclusion
---
*Generated by AI Business Operator*

Use professional language, include specific data, ready for executive presentation."""

MARKETING_SYSTEM = """You are a marketing content specialist.
For LinkedIn posts: hook + short paragraphs + 3-5 hashtags + CTA (150-300 words each).
Create multiple pieces, each clearly labelled."""

class ContentAgent(BaseAgent):
    name = "ContentAgent"
    description = "Writes reports and marketing content"

    def run(self, task: str, context: Dict[str, Any] = None) -> Dict[str, Any]:
        context    = context or {}
        plan       = context.get("plan", {})
        research   = context.get("research_output", "")
        analysis   = context.get("analysis_output", "")
        output_dir = context.get("output_dir", "./reports")
        task_type  = plan.get("task_type", "market_research")
        self._log(f"Writing {plan.get('output_format','report')} content…")

        is_marketing = task_type == "content_creation" or any(w in task.lower() for w in ("post","linkedin","marketing","content","tweet"))
        system  = MARKETING_SYSTEM if is_marketing else REPORT_SYSTEM.format(date=datetime.now().strftime("%B %d, %Y"))
        prompt  = f"Task: {task}\n\nResearch:\n{research[:2500]}\n\nAnalysis:\n{analysis[:2500]}"
        content = self._call_llm(system, prompt, max_tokens=2000, temperature=0.5)

        report_path = self._save_md(content, task, output_dir)
        pdf_path    = self._save_pdf(content, task, output_dir)

        return {
            "agent": self.name, "output": content,
            "report_path": report_path, "pdf_path": pdf_path,
            "word_count": len(content.split()),
        }

    def _save_md(self, content: str, task: str, output_dir: str) -> str:
        try:
            Path(output_dir).mkdir(parents=True, exist_ok=True)
            ts   = datetime.now().strftime("%Y%m%d_%H%M%S")
            name = "".join(c if c.isalnum() else "_" for c in task[:30])
            p    = Path(output_dir) / f"report_{name}_{ts}.md"
            p.write_text(content, encoding="utf-8")
            return str(p)
        except Exception as e:
            self._log(f"MD save failed: {e}"); return ""

    def _save_pdf(self, content: str, task: str, output_dir: str) -> str:
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import cm
            from reportlab.lib import colors
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
            import re

            Path(output_dir).mkdir(parents=True, exist_ok=True)
            ts   = datetime.now().strftime("%Y%m%d_%H%M%S")
            name = "".join(c if c.isalnum() else "_" for c in task[:30])
            pdf_path = Path(output_dir) / f"report_{name}_{ts}.pdf"

            doc   = SimpleDocTemplate(str(pdf_path), pagesize=A4,
                                      leftMargin=2.5*cm, rightMargin=2.5*cm,
                                      topMargin=2*cm, bottomMargin=2*cm)
            styles = getSampleStyleSheet()
            h1 = ParagraphStyle("H1", parent=styles["Heading1"], fontSize=18, spaceAfter=12,
                                 textColor=colors.HexColor("#1a1a2e"))
            h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=13, spaceAfter=8,
                                 textColor=colors.HexColor("#1a1a2e"))
            bd = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, spaceAfter=6, leading=15)
            bl = ParagraphStyle("Bullet", parent=styles["Normal"], fontSize=10,
                                 leftIndent=15, spaceAfter=4, leading=13)

            story = []
            for line in content.split("\n"):
                line = line.strip()
                if not line: story.append(Spacer(1, 5)); continue
                if line.startswith("# "):
                    story.append(Paragraph(line[2:], h1))
                    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a1a2e")))
                elif line.startswith("## "):
                    story.append(Spacer(1, 8)); story.append(Paragraph(line[3:], h2))
                elif line.startswith(("- ", "* ")):
                    story.append(Paragraph(f"• {line[2:]}", bl))
                elif line.startswith("---"):
                    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
                else:
                    clean = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", line)
                    story.append(Paragraph(clean, bd))

            doc.build(story)
            return str(pdf_path)
        except Exception as e:
            self._log(f"PDF failed: {e}"); return ""
