"""
agents/content_agent.py — Content Generator Agent
Produces polished business documents: full reports, executive summaries,
marketing posts, LinkedIn content, and PDF-ready reports.
"""
from __future__ import annotations
from datetime import datetime
from typing import Dict, Any, List
from pathlib import Path
from .base_agent import BaseAgent


REPORT_SYSTEM = """You are the Content Agent in an autonomous AI Business Operator system.
You produce polished, professional business content from research and analysis data.

Write a complete, professional business report with this structure:

# [Report Title]
**Prepared by:** AI Business Operator  
**Date:** {date}  
**Classification:** Business Intelligence Report

---

## Executive Summary
[3-4 sentences capturing the most important insights]

## Market Overview
[Comprehensive market description with data]

## Competitive Analysis
[Detailed competitor breakdown]

## Key Trends & Insights
[Trends with implications]

## SWOT Analysis
[Full SWOT with context]

## Strategic Recommendations
[5 actionable recommendations with rationale]

## Conclusion
[2-3 sentence wrap-up]

---
*This report was generated by AI Business Operator. Data sourced from web research.*

Use professional language, include specific data points, and make it ready for executive presentation.
Format with proper markdown headers, bullet points, and tables where appropriate."""


MARKETING_SYSTEM = """You are the Content Agent specializing in marketing content creation.
Generate high-quality, platform-optimized marketing content.

For LinkedIn posts:
- Start with a hook (question, statistic, or bold statement)
- Use short paragraphs (2-3 lines max)
- Include 3-5 relevant hashtags
- End with a call-to-action
- Length: 150-300 words per post

For blog posts:
- SEO-optimized title
- Engaging intro paragraph
- Structured with H2/H3 subheadings
- Include data and examples
- Clear conclusion with CTA

Create multiple variations if requested."""


class ContentAgent(BaseAgent):
    name = "ContentAgent"
    description = "Generates reports, marketing posts, and business documents"

    def run(self, task: str, context: Dict[str, Any] = None) -> Dict[str, Any]:
        context = context or {}
        plan = context.get("plan", {})
        research_output = context.get("research_output", "")
        analysis_output = context.get("analysis_output", "")
        chart_paths = context.get("chart_paths", [])
        output_format = plan.get("output_format", "report")
        task_type = plan.get("task_type", "market_research")

        self._log(f"Generating {output_format} content for task type: {task_type}")

        # Route to appropriate content generator
        if task_type == "content_creation" or "post" in task.lower() or "marketing" in task.lower():
            content = self._generate_marketing_content(task, research_output, analysis_output)
        else:
            content = self._generate_business_report(task, research_output, analysis_output)

        # Save markdown report
        output_dir = context.get("output_dir", "./reports")
        report_path = self._save_report(content, task, output_dir)

        # Try to generate PDF
        pdf_path = self._generate_pdf(content, task, output_dir)

        self._log(f"Content generated. Report saved: {report_path}")

        return {
            "agent": self.name,
            "output": content,
            "report_path": report_path,
            "pdf_path": pdf_path,
            "chart_paths": chart_paths,
            "word_count": len(content.split()),
        }

    def _generate_business_report(self, task: str, research: str, analysis: str) -> str:
        date = datetime.now().strftime("%B %d, %Y")
        system = REPORT_SYSTEM.format(date=date)

        prompt = f"""
Task: {task}

Research Findings:
{research[:3000]}

Analysis Results:
{analysis[:3000]}

Generate a complete professional business report.
"""
        return self._call_llm(system, prompt, max_tokens=2000, temperature=0.4)

    def _generate_marketing_content(self, task: str, research: str, analysis: str) -> str:
        prompt = f"""
Task: {task}

Research Context:
{research[:1500]}

Analysis Insights:
{analysis[:1500]}

Generate the requested marketing content.
"""
        return self._call_llm(MARKETING_SYSTEM, prompt, max_tokens=1500, temperature=0.7)

    def _save_report(self, content: str, task: str, output_dir: str) -> str:
        """Save the report as a markdown file."""
        try:
            Path(output_dir).mkdir(parents=True, exist_ok=True)
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            safe_name = "".join(c if c.isalnum() else "_" for c in task[:30])
            path = Path(output_dir) / f"report_{safe_name}_{ts}.md"
            path.write_text(content, encoding="utf-8")
            return str(path)
        except Exception as e:
            self._log(f"Could not save report: {e}")
            return ""

    def _generate_pdf(self, content: str, task: str, output_dir: str) -> str:
        """Generate a PDF version of the report using reportlab."""
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import cm
            from reportlab.lib import colors
            from reportlab.platypus import (
                SimpleDocTemplate, Paragraph, Spacer,
                HRFlowable, Table, TableStyle,
            )
            import re

            Path(output_dir).mkdir(parents=True, exist_ok=True)
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            safe_name = "".join(c if c.isalnum() else "_" for c in task[:30])
            pdf_path = Path(output_dir) / f"report_{safe_name}_{ts}.pdf"

            doc = SimpleDocTemplate(
                str(pdf_path),
                pagesize=A4,
                leftMargin=2.5 * cm,
                rightMargin=2.5 * cm,
                topMargin=2 * cm,
                bottomMargin=2 * cm,
            )

            styles = getSampleStyleSheet()
            story = []

            h1_style = ParagraphStyle("H1", parent=styles["Heading1"],
                                      fontSize=18, spaceAfter=12, textColor=colors.HexColor("#1a1a2e"))
            h2_style = ParagraphStyle("H2", parent=styles["Heading2"],
                                      fontSize=13, spaceAfter=8, textColor=colors.HexColor("#1a1a2e"))
            body_style = ParagraphStyle("Body", parent=styles["Normal"],
                                        fontSize=10, spaceAfter=6, leading=15)
            bullet_style = ParagraphStyle("Bullet", parent=styles["Normal"],
                                          fontSize=10, leftIndent=15, spaceAfter=4, leading=13)

            # Parse markdown to flowables
            lines = content.split("\n")
            for line in lines:
                line = line.strip()
                if not line:
                    story.append(Spacer(1, 6))
                    continue
                if line.startswith("# "):
                    story.append(Paragraph(line[2:], h1_style))
                    story.append(HRFlowable(width="100%", thickness=1,
                                            color=colors.HexColor("#1a1a2e"), spaceAfter=8))
                elif line.startswith("## "):
                    story.append(Spacer(1, 10))
                    story.append(Paragraph(line[3:], h2_style))
                elif line.startswith("### "):
                    story.append(Paragraph(f"<b>{line[4:]}</b>", body_style))
                elif line.startswith("- ") or line.startswith("* "):
                    text = line[2:].replace("**", "<b>", 1).replace("**", "</b>", 1)
                    story.append(Paragraph(f"• {text}", bullet_style))
                elif line.startswith("**") and line.endswith("**"):
                    story.append(Paragraph(f"<b>{line[2:-2]}</b>", body_style))
                elif line.startswith("---"):
                    story.append(HRFlowable(width="100%", thickness=0.5,
                                            color=colors.grey, spaceAfter=6))
                else:
                    clean = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", line)
                    story.append(Paragraph(clean, body_style))

            doc.build(story)
            self._log(f"PDF generated: {pdf_path}")
            return str(pdf_path)

        except Exception as e:
            self._log(f"PDF generation failed: {e}")
            return ""
